/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/mobius_house.glb --shadows --transform 
Files: public/mobius_house.glb [2.17MB] > C:\Users\Mubarak\Documents\Projects\house\mobius_house-transformed.glb [273.02KB] (87%)
Author: fantecboisseau (https://sketchfab.com/fantecboisseau)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mobius-house-e9286d982bb445d7a0d82558160db0c1
Title: MOBIUS HOUSE
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function House(props) {
  const { nodes, materials } = useGLTF("/mobius_house.glb");
  return (
    <group
      {...props}
      dispose={null}
      position={[400, -50, 30]}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BATI_APPART_BATI_APPART_0.geometry}
        material={materials.BATI_APPART}
        position={[-2162.324, -759.796, 10882.633]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BATI_BATI_0.geometry}
        material={materials.BATI}
        position={[-2162.325, -759.796, 10882.633]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.VITRES_VITRES_0.geometry}
        material={materials.VITRES}
        position={[-2162.325, -759.796, 10882.633]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SOCLE_SOCLE_0.geometry}
        material={materials.SOCLE}
        position={[200.175, -120.987, -757.916]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.COUPE_TERRAIN_BAKETERRE_0.geometry}
        material={materials["BAKE.TERRE"]}
        position={[-2162.325, -759.796, 10882.633]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.COUPE_TERRAIN_BAKETRAIT_COUPE_0.geometry}
        material={materials["BAKE.TRAIT_COUPE"]}
        position={[-2162.325, -759.796, 10882.633]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/mobius_house.glb");
